version: '3.7'

services:
  drone-server:
    container_name: drone
    image: 'drone/drone:1'
    ports:
      - 8000:80
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/lib/drone:/data'
    restart: always
    env_file:
      - /etc/drone/server.env
  drone-runner:
    container_name: drone_runner
    image: 'drone/drone-runner-docker:1'
    restart: always
    depends_on:
      - drone-server
    ports:
      - 3000:3000
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
      restart_policy:
        condition: on-failure
    env_file:
      - /etc/drone/runner.env
